apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-from-curl
  namespace: team-a
spec:
  podSelector:
    matchLabels:
      app: team-a-app

  policyTypes:
  - Ingress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: nginx-team-a
    ports:
    - protocol: TCP
      port: 80
