apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-b-ingress
  namespace: team-b
spec:
  rules:
  - host: team-b.policy.com
    http:
      paths:
      - backend:
          service:
            name: team-b-app
            port:
              number: 80
        path: /
        pathType: Exact
status:
  loadBalancer: {}
